# Generated by Django 4.1.3 on 2022-11-24 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='administrator',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='编号')),
                ('name', models.CharField(max_length=20, verbose_name='姓名')),
                ('age', models.IntegerField(null=True, verbose_name='年龄')),
                ('sex', models.BooleanField(null=True, verbose_name='性别')),
                ('mobile', models.CharField(max_length=20, verbose_name='手机')),
            ],
            options={
                'db_table': 'administrator',
            },
        ),
        migrations.CreateModel(
            name='court',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='编号')),
                ('location', models.CharField(max_length=20, verbose_name='位置')),
                ('service_start_time', models.IntegerField(verbose_name='开始时间')),
                ('service_end_time', models.IntegerField(verbose_name='结束时间')),
            ],
            options={
                'db_table': 'court',
            },
        ),
        migrations.CreateModel(
            name='customer',
            fields=[
                ('mobile', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='手机')),
                ('name', models.CharField(max_length=20, verbose_name='姓名')),
                ('age', models.IntegerField(null=True, verbose_name='年龄')),
                ('sex', models.BooleanField(default=True, null=True, verbose_name='性别')),
            ],
            options={
                'db_table': 'customer',
            },
        ),
        migrations.CreateModel(
            name='status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('court_id', models.IntegerField(verbose_name='球场编号')),
                ('administrator_id', models.IntegerField(verbose_name='管理人员编号')),
                ('customer', models.CharField(max_length=20, verbose_name='预定人员手机号')),
                ('occupy_year', models.IntegerField(null=True, verbose_name='开始年份')),
                ('occupy_month', models.IntegerField(null=True, verbose_name='开始月份')),
                ('occupy_date', models.IntegerField(null=True, verbose_name='开始日期')),
                ('occupy_hour', models.IntegerField(null=True, verbose_name='开始时间')),
            ],
            options={
                'db_table': 'status',
            },
        ),
    ]
